
name: Deploy AWS Lambda

on:
  push:
    branches:
      - main
    paths:
      - 'lambda/**'

permissions:
  contents: read

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          mkdir lambda/package
          pip install -r lambda/requirements.txt -t lambda/package
          cp lambda/*.py lambda/package/

      - name: Validate Lambda
        run: |
          python -m compileall lambda/package

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Package Lambda
        run: |
          cd lambda/package
          zip -r ../lambda.zip .

      - name: Deploy Lambda Function
        run: |
          aws lambda update-function-code \
            --function-name my-test-cicd-lambda \
            --zip-file fileb://lambda/lambda.zip